[package]
name = "grin_pool"
version = "0.3.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = '..'
publish = false

[dependencies]
blake2-rfc = "0.2"
rand = "0.5"
serde = "1"
serde_derive = "1"
slog = { version = "~2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.4"

grin_core = { path = "../core" }
grin_keychain = { path = "../keychain" }
grin_store = { path = "../store" }
grin_util = { path = "../util" }

[dev-dependencies]
grin_wallet = { path = "../wallet" }
grin_chain = { path = "../chain" }
