[package]
name = "grin_store"
version = "1.0.1"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
description = "Simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/grin"
keywords = [ "crypto", "grin", "mimblewimble" ]
workspace = ".."
edition = "2018"

[dependencies]
byteorder = "1"
croaring = "=0.3.8"
env_logger = "0.5"
libc = "0.2"
failure = "0.1"
failure_derive = "0.1"
lmdb-zero = "0.4.4"
memmap = "0.7"
serde = "1"
serde_derive = "1"
log = "0.4"

grin_core = { path = "../core", version = "1.0.1" }
grin_util = { path = "../util", version = "1.0.1" }

[dev-dependencies]
chrono = "0.4.4"
rand = "0.5"
filetime = "0.2"
