[package]
name = "grin_store"
version = "0.3.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = ".."
publish = false

[dependencies]
byteorder = "1"
croaring = "=0.3"
env_logger = "0.5"
libc = "0.2"
failure = "0.1"
failure_derive = "0.1"
lmdb-zero = "0.4.4"
memmap = "0.6.2"
serde = "1"
serde_derive = "1"
slog = { version = "~2.3", features = ["max_level_trace", "release_max_level_trace"] }

grin_core = { path = "../core" }
grin_util = { path = "../util" }

[dev-dependencies]
chrono = "0.4.4"
rand = "0.3"
