[package]
name = "grin_store"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]
workspace = ".."

[dependencies]
byteorder = "^0.5"
env_logger="^0.3.5"
slog = { version = "^2.0.12", features = ["max_level_trace", "release_max_level_trace"] }
libc = "^0.2"
memmap = { git = "https://github.com/danburkert/memmap-rs", tag="0.6.0" }
rocksdb = "^0.7.0"

grin_core = { path = "../core" }
grin_util = { path = "../util" }

[dev-dependencies]
time = "^0.1"
