[package]
name = "grin_p2p"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]
workspace = ".."

[dependencies]
bitflags = "^0.7.0"
byteorder = "^0.5"
futures = "^0.1.9"
log = "^0.3"
net2 = "0.2.0"
rand = "^0.3"
serde = "~1.0.8"
serde_derive = "~1.0.8"
tokio-core="^0.1.1"
tokio-timer="^0.1.0"
time = "^0.1"
enum_primitive = "^0.1.0"
num = "^0.1.36"

grin_core = { path = "../core" }
grin_store = { path = "../store" }
grin_util = { path = "../util" }

[dev-dependencies]
env_logger = "^0.3"
secp256k1zkp = { path = "../secp256k1zkp" }
