[package]
name = "grin_p2p"
version = "0.1.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = ".."
publish = false

[dependencies]
bitflags = "^1.0"
slog = { version = "^2.0.12", features = ["max_level_trace", "release_max_level_trace"] }
net2 = "0.2.0"
rand = "^0.3"
serde = "~1.0.8"
serde_derive = "~1.0.8"
bytes = "0.4.3"
time = "^0.1"
enum_primitive = "^0.1.0"
num = "^0.1.36"

grin_core = { path = "../core" }
grin_store = { path = "../store" }
grin_util = { path = "../util" }
