[package]
name = "grin_p2p"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]
workspace = ".."

[dependencies]
bitflags = "^0.7.0"
byteorder = "^0.5"
futures = "^0.1.15"
slog = { version = "^2.0.12", features = ["max_level_trace", "release_max_level_trace"] }
net2 = "0.2.0"
rand = "^0.3"
serde = "~1.0.8"
serde_derive = "~1.0.8"
bytes = "0.4.3"
tokio-core="^0.1.1"
tokio-timer="^0.1.0"
tokio-io="^0.1"
time = "^0.1"
enum_primitive = "^0.1.0"
num = "^0.1.36"

grin_core = { path = "../core" }
grin_store = { path = "../store" }
grin_util = { path = "../util" }
