[package]
name = "grin_util"
version = "0.1.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = ".."
publish = false

[dependencies]
backtrace = "0.3"
byteorder = "1"
lazy_static = "0.2"
rand = "0.3"
serde = "1"
serde_derive = "1"
slog = { version = "2.1", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.1"
slog-async = "2.1"
walkdir = "2"
zip = "0.2"

[dependencies.secp256k1zkp]
git = "https://github.com/mimblewimble/rust-secp256k1-zkp"
tag = "grin_integration_16"
#path = "../../rust-secp256k1-zkp"
features = ["bullet-proof-sizing"]
