[package]
name = "grin_util"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>",
           "Yeastplume <yeastplume@protonmail.com>"]
workspace = ".."

[dependencies]
slog = { version = "^2.0.12", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "^2.2.0"
slog-async = "^2.1.0"
lazy_static = "~0.2.8"
byteorder = "^1.0"
rand = "^0.3"
serde = "~1.0.8"
serde_derive = "~1.0.8"
walkdir = "^2.0.1"
zip = "^0.2.6"

[dependencies.secp256k1zkp]
git = "https://github.com/mimblewimble/rust-secp256k1-zkp"
tag="grin_integration_15"
#path = "../../rust-secp256k1-zkp"
features=["bullet-proof-sizing"]
