[package]
name = "grin_config"
version = "0.1.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = ".."
publish = false

[dependencies]
serde = "1"
serde_derive = "1"
toml = "0.4"

grin_grin = { path = "../grin" }
grin_p2p = { path = "../p2p" }
grin_pow = { path = "../pow"}
grin_util = { path = "../util" }
grin_wallet = { path = "../wallet"}
