[package]
name = "grin_config"
version = "0.3.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = ".."
publish = false

[dependencies]
serde = "1"
serde_derive = "1"
toml = "0.4"
dirs = "1.0.3"

grin_servers = { path = "../servers" }
grin_p2p = { path = "../p2p" }
grin_util = { path = "../util" }
grin_wallet = { path = "../wallet"}

[dev-dependencies]
pretty_assertions = "0.5.1"
