[package]
name = "grin_api"
version = "0.3.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
workspace = ".."
publish = false

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
hyper = "0.12"
lazy_static = "1"
mount = "0.3"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
slog = { version = "~2.2", features = ["max_level_trace", "release_max_level_trace"] }
tokio = "0.1.7"
tokio-core = "0.1.17"
http = "0.1.5"
futures = "0.1.21"
url = "1.7.0"

grin_core = { path = "../core" }
grin_chain = { path = "../chain" }
grin_p2p = { path = "../p2p" }
grin_pool = { path = "../pool" }
grin_store = { path = "../store" }
grin_util = { path = "../util" }
